"""
Build Progress Routes
=====================
SSE endpoint for streaming build progress events to the frontend.
"""

import asyncio
import json
from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse

from api.deps import get_current_user, AuthenticatedUser
from services.project_service import get_project_service

router = APIRouter(prefix="/api/v1/build", tags=["Build"])


# =============================================================================
# Build Pipeline Stages
# =============================================================================

BUILD_STAGES = [
    {"id": "architect", "label": "Architect", "duration": 3.0},
    {"id": "frontend", "label": "Frontend", "duration": 5.0},
    {"id": "backend", "label": "Backend", "duration": 4.0},
    {"id": "testing", "label": "Testing", "duration": 2.0},
    {"id": "review", "label": "Review", "duration": 2.0},
    {"id": "done", "label": "Done", "duration": 0.5},
]


def sse_event(data: dict) -> str:
    """Format a dict as an SSE event."""
    return f"data: {json.dumps(data)}\n\n"


# =============================================================================
# SSE Endpoint
# =============================================================================


@router.get("/{project_id}/stream")
async def stream_build_progress(
    project_id: str, user: AuthenticatedUser = Depends(get_current_user)
):
    """
    Stream build progress events via SSE.

    Events:
    - node_start: A pipeline node has started
    - node_complete: A pipeline node has finished
    - node_error: A pipeline node has failed
    - build_complete: The entire build is done

    In production, this will be driven by real multi-agent events.
    For now, it simulates progress with timed stages.
    """
    service = get_project_service()
    project = service.get(project_id)

    async def event_generator():
        # If project doesn't exist, send error and close
        if not project:
            yield sse_event(
                {
                    "type": "node_error",
                    "node_id": "architect",
                    "message": "Project not found",
                }
            )
            return

        # Ownership check — prevent cross-tenant IDOR
        owner = getattr(project, "user_id", None) or getattr(project, "owner_id", None)
        if owner is not None and owner != user.id:
            yield sse_event(
                {
                    "type": "node_error",
                    "node_id": "architect",
                    "message": "Access denied",
                }
            )
            return

        # Simulate pipeline execution
        for stage in BUILD_STAGES:
            # Node start
            yield sse_event(
                {
                    "type": "node_start",
                    "node_id": stage["id"],
                    "label": stage["label"],
                }
            )

            # Simulate work
            await asyncio.sleep(stage["duration"])

            # Node complete
            yield sse_event(
                {
                    "type": "node_complete",
                    "node_id": stage["id"],
                    "label": stage["label"],
                }
            )

        # Generate sample files for the project
        sample_files = _generate_sample_files(project.category, project.description)
        service.update_files(project_id, sample_files)
        service.update(project_id, status="ready")

        # Build complete
        yield sse_event(
            {
                "type": "build_complete",
                "project_id": project_id,
                "files_count": len(sample_files),
            }
        )

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",  # Disable nginx buffering
        },
    )


# =============================================================================
# Phase 4.0: ZIP Download with Native SDK
# =============================================================================

VOS3_SDK_H = """\
/**
 * VOS3 Native SDK — Syscall Stubs for VOS3 Kernel
 * =================================================
 * Phase 4.0: Auto-generated by VBuilder.
 * Link with musl libc: x86_64-linux-musl-gcc -static -o app main.c
 */
#ifndef VOS3_SDK_H
#define VOS3_SDK_H

#include <stdint.h>
#include <stddef.h>

/* VOS3 syscall numbers (Linux x86_64 ABI) */
#define VOS3_SYS_READ       0
#define VOS3_SYS_WRITE      1
#define VOS3_SYS_OPEN       2
#define VOS3_SYS_CLOSE       3
#define VOS3_SYS_FSTAT       5
#define VOS3_SYS_LSEEK      8
#define VOS3_SYS_MMAP        9
#define VOS3_SYS_MUNMAP     11
#define VOS3_SYS_BRK        12
#define VOS3_SYS_EXIT       60
#define VOS3_SYS_GETPID    39
#define VOS3_SYS_GETCWD    79
#define VOS3_SYS_OPENAT   257
#define VOS3_SYS_EXIT_GROUP 231
#define VOS3_SYS_GETRANDOM 318

static inline long vos3_syscall1(long nr, long a1) {
    long ret;
    __asm__ volatile ("syscall" : "=a"(ret) : "a"(nr), "D"(a1)
                      : "rcx", "r11", "memory");
    return ret;
}

static inline long vos3_syscall2(long nr, long a1, long a2) {
    long ret;
    __asm__ volatile ("syscall" : "=a"(ret) : "a"(nr), "D"(a1), "S"(a2)
                      : "rcx", "r11", "memory");
    return ret;
}

static inline long vos3_syscall3(long nr, long a1, long a2, long a3) {
    long ret;
    register long r10 __asm__("r10") = a3;
    __asm__ volatile ("syscall" : "=a"(ret) : "a"(nr), "D"(a1), "S"(a2), "d"(a3)
                      : "rcx", "r11", "memory");
    (void)r10;
    return ret;
}

/* Convenience wrappers */
static inline void vos3_exit(int code) { vos3_syscall1(VOS3_SYS_EXIT, code); }
static inline long vos3_write(int fd, const void *buf, size_t count) {
    return vos3_syscall3(VOS3_SYS_WRITE, fd, (long)buf, count);
}
static inline long vos3_read(int fd, void *buf, size_t count) {
    return vos3_syscall3(VOS3_SYS_READ, fd, (long)buf, count);
}

/* Helper: write string to stdout */
static inline void vos3_puts(const char *s) {
    size_t len = 0;
    while (s[len]) len++;
    vos3_write(1, s, len);
}

#endif /* VOS3_SDK_H */
"""

MAKEFILE_NATIVE = """\
# VOS3 Native Build — musl cross-compilation
# Usage: make          (builds app.elf)
#        make clean    (removes build artifacts)

CC      = x86_64-linux-musl-gcc
CFLAGS  = -static -Os -Wall -Wextra -nostdinc -ffreestanding
LDFLAGS = -static -nostdlib
TARGET  = app.elf
SRCS    = $(wildcard *.c)
OBJS    = $(SRCS:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJS)
\t$(CC) $(LDFLAGS) -o $@ $^

%.o: %.c
\t$(CC) $(CFLAGS) -c -o $@ $<

clean:
\trm -f $(TARGET) $(OBJS)

.PHONY: all clean
"""


@router.get("/{project_id}/download")
async def download_project_zip(
    project_id: str, user: AuthenticatedUser = Depends(get_current_user)
):
    """Download project as ZIP with VOS3 Native SDK included."""
    import io
    import zipfile as zf
    from fastapi.responses import StreamingResponse as ZipStreamingResponse

    service = get_project_service()
    project = service.get(project_id)
    if not project:
        from fastapi import HTTPException

        raise HTTPException(status_code=404, detail="Project not found")

    # Ownership check — prevent cross-tenant IDOR
    from fastapi import HTTPException as _HTTPException

    owner = getattr(project, "user_id", None) or getattr(project, "owner_id", None)
    if owner is not None and owner != user.id:
        raise _HTTPException(status_code=403, detail="Access denied")

    buf = io.BytesIO()
    with zf.ZipFile(buf, "w", zf.ZIP_DEFLATED) as z:
        # Project files
        files = getattr(project, "files", None) or {}
        for path, content in files.items():
            z.writestr(path, content)
        # Native SDK
        z.writestr("vos3/VOS3_SDK.h", VOS3_SDK_H)
        z.writestr("vos3/Makefile.native", MAKEFILE_NATIVE)

    buf.seek(0)
    return ZipStreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{project_id}.zip"'},
    )


def _generate_sample_files(category: str, description: str) -> dict:
    """Generate sample project files based on category. In production, this comes from the multi-agent pipeline."""
    return {
        "package.json": json.dumps(
            {
                "name": f"v-creator-{category}",
                "version": "1.0.0",
                "private": True,
                "scripts": {
                    "dev": "vite",
                    "build": "vite build",
                },
                "dependencies": {
                    "react": "^18.3.0",
                    "react-dom": "^18.3.0",
                },
                "devDependencies": {
                    "@vitejs/plugin-react": "^4.2.0",
                    "vite": "^5.0.0",
                },
            },
            indent=2,
        ),
        "index.html": f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>My {category.title()}</title>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.tsx"></script>
</body>
</html>""",
        "src/main.tsx": """import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);""",
        "src/App.tsx": f"""import React from 'react';

export default function App() {{
  return (
    <div style={{ fontFamily: 'Inter, sans-serif', minHeight: '100vh', backgroundColor: '#fafafa' }}>
      <header style={{ padding: '24px 32px', borderBottom: '1px solid #eee' }}>
        <h1 style={{ margin: 0, fontSize: '20px' }}>My {category.title()}</h1>
      </header>
      <main style={{ maxWidth: '960px', margin: '0 auto', padding: '48px 24px' }}>
        <h2>Welcome!</h2>
        <p>{description[:200]}</p>
      </main>
    </div>
  );
}}""",
        "src/index.css": """*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
}

body {
  font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
  -webkit-font-smoothing: antialiased;
}""",
    }
