// Generate real runtime helpers and schema-derived types with the installed
// Convex templates. This is local code generation; it does not deploy anything.
import { readdir, mkdir, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const convexRoot = path.dirname(require.resolve('convex/package.json'));
const templates = path.join(convexRoot, 'dist/esm/cli/codegen_templates');
const { apiCodegen } = await import(pathToFileURL(path.join(templates, 'api.js')));
const { serverCodegen } = await import(pathToFileURL(path.join(templates, 'server.js')));

async function modules(directory, prefix = '') {
  const result = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.name.startsWith('_') || entry.name.startsWith('.')) continue;
    const relative = prefix + entry.name;
    if (entry.isDirectory()) result.push(...await modules(path.join(directory, entry.name), relative + '/'));
    else if (entry.name.endsWith('.ts') && !entry.name.endsWith('.d.ts')
             && !['schema.ts', 'auth.config.ts', 'convex.config.ts'].includes(entry.name)) result.push(relative);
  }
  return result.sort();
}

const generated = path.join(root, 'convex/_generated');
await mkdir(generated, { recursive: true });
const modulePaths = await modules(path.join(root, 'convex'));
await writeFile(path.join(generated, 'api.ts'), apiCodegen(modulePaths, { useTypeScript: true }).TS);
await writeFile(path.join(generated, 'server.ts'), serverCodegen({ useTypeScript: true }).TS);
// Convex's schema-based data model uses only public types. Keep this small
// equivalent here to avoid loading deployment-only CLI dependencies offline.
await writeFile(path.join(generated, 'dataModel.ts'), `// Generated by scripts/generate-convex.mjs; derived from the actual schema.
import type { DataModelFromSchemaDefinition, DocumentByName, TableNamesInDataModel, SystemTableNames } from "convex/server";
import type { GenericId } from "convex/values";
import type schema from "../schema.js";
export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
export type TableNames = TableNamesInDataModel<DataModel>;
export type Doc<TableName extends TableNames> = DocumentByName<DataModel, TableName>;
export type Id<TableName extends TableNames | SystemTableNames> = GenericId<TableName>;
`);
console.log(`Generated runtime helpers and types for ${modulePaths.length} Convex modules.`);
