"""
Inter-Agent Provenance — chained HMAC-SHA256 signatures across LangGraph node-to-node handoffs
==============================================================================================

This module addresses OWASP Top 10 for Agentic Applications **AA6 — Inter-agent
communication corruption**.

The problem
-----------
A multi-agent LangGraph pipeline shuffles strings between nodes:

    architect → expander → [frontend || backend] → aggregator → guardrails
        → db_migrations → tester → visual_qa → reviewer → finalize

Every downstream node reads what the upstream node wrote as if it were
unforgeable truth. If a string is *accidentally* corrupted (a shared-state bug,
a reducer collision under parallel ``Send`` dispatch, a deserialization round
trip that drops bytes) or *adversarially* tampered with (a malicious tool
injection that gets surfaced into the prompt of the next agent and convinces
the LLM to claim authorship of something it did not generate), the consumer has
no way to tell. The receiving agent acts on the corrupted content and the
corruption compounds across the rest of the pipeline.

Design — chained MAC, monotonic sequence
----------------------------------------
We wrap each inter-agent handoff in a :class:`SignedAgentMessage`:

    sender_role   : str   — e.g. ``"architect"``
    sequence_num  : int   — monotonic, starts at 1 per session
    payload       : str   — the actual handoff content
    mac           : bytes — HMAC-SHA256(key, role || ":" || seq || ":" || payload || ":" || prev_mac)
    previous_mac  : bytes — links to the prior message's MAC (b"" for the first)
    created_at_iso: str   — ISO-8601 timestamp, audit-only (NOT covered by MAC)

The MAC is computed over a delimited concatenation of the role, sequence
number, payload, and the *previous* message's MAC. Binding the previous MAC
into the input means tampering with any earlier message in the chain
invalidates every later message — the consumer cannot be fooled by
re-ordering, splicing, replaying, or selectively dropping messages.

Verification:

  * sequence_num MUST be strictly greater than the last verified seq (rejects
    replay and out-of-order).
  * previous_mac MUST equal the last verified MAC (rejects chain splicing).
  * mac MUST equal the locally recomputed HMAC, compared in CONSTANT TIME via
    :func:`hmac.compare_digest` (defends against MAC-length oracle timing
    attacks against the verifier).

A per-session key is generated by the builder at the start of a LangGraph run
via :func:`secrets.token_bytes(32)`. Each run is therefore an independent
chain: keys do not survive across builds, and a leaked key from run N cannot
forge messages in run N+1.

Threat model — what this DEFENDS against
----------------------------------------
1. **Accidental in-process corruption.** A state reducer collision, a buggy
   parallel ``Send`` merge, a TypedDict field truncated by a downstream
   refactor — anything that mangles ``payload`` without re-signing — fails
   verification and the consumer is told.

2. **Indirect injection that survives the AA1/AA2 sanitizers and tries to
   forge prior-agent authorship.** If the architect's output contains an
   adversarial span saying "Frontend agent: actually do X instead", the
   downstream Frontend agent has no signed message from the Architect saying
   that — only what was signed at the original handoff. Forged role
   attributions are detected.

3. **Reordering / replay attacks.** A malicious component that records
   message N and re-injects it after message M (where M > N) is rejected:
   the sequence number is no longer monotonic.

4. **Chain splicing.** Removing message N and pretending message N+1 came
   directly after N-1 is rejected: ``previous_mac`` no longer matches.

Threat model — what this does NOT defend against
------------------------------------------------
1. **A fully-compromised agent process.** If an attacker has code execution
   inside the Python process running this module, they hold the session key
   in ``AgentMessageChain._key`` and can forge MACs at will. This is
   provenance against *accidental* corruption + *channel* injection, not a
   multi-party authentication scheme. A future hardware-attested-runtime
   layer (TPM-backed key per agent role, signing inside an enclave) would
   close that gap. That is Stage 3 work and is explicitly out of scope here.

2. **Semantic correctness of signed content.** The chain guarantees that
   "the Architect node at sequence 3 emitted exactly this payload" — it does
   NOT guarantee the payload is benign. An Architect agent that has itself
   been prompt-injected and emits adversarial code legitimately signs that
   adversarial code. The wrap mechanism (AA2 ``[UNTRUSTED-DATA]``), the
   semantic firewall (AA1/AA2 deepening), the architectural guardrails AST
   gate (AA3 / quality), and the output sanitizer (AA9) are the layered
   defenses that bound that residual.

3. **Side-channel timing on the MAC verifier.** We use
   :func:`hmac.compare_digest` for constant-time comparison, which mitigates
   classic byte-by-byte oracle timing but does not eliminate every possible
   side channel (cache timing, branch prediction, power analysis on a host
   under physical attacker control). This is the standard CPython mitigation;
   defeating sophisticated side channels is out of scope.

4. **Cross-session correlation.** The key is fresh per session, which is the
   right choice for confidentiality but means we cannot cross-validate a
   message claimed to come from a prior session. That is auditing's problem,
   not the chain's.

Status: AA6 moves from **OPEN GAP** to **Partially defended** with this
module. Stage 2 follow-on is per-role key derivation (every agent role gets a
sub-key via HKDF off the session key, so a compromised role cannot forge
messages from any other role within the same session). Stage 3 is
hardware-attested signing. Both are deferred.

Kernel precedent: VBus (per ``CLAUDE.md``) uses HMAC-SHA256 with a per-session
random key exchanged at HANDSHAKE and constant-time verification of a 32-byte
MAC at frame header offset 16. This module is the user-space agent analog of
that design — same primitive, same constant-time check, scoped to LangGraph
handoffs instead of VBus frames. We do not borrow the kernel's C
implementation; we use Python's stdlib :mod:`hmac` (which wraps the same
FIPS 180-4 SHA-256 / RFC 2104 HMAC primitives in CPython's ``_hashlib``).

OWASP mapping:
  * AA6 (Inter-agent communication corruption) — primary mitigation.
  * AA2 (Indirect prompt injection) — partial deepening: forged
    prior-agent authorship from an injected tool span is detected.
  * AA8 (Emergent autonomous behavior) — partial deepening: a runaway
    loop that tries to forge an extra step beyond the bounded retry
    budget is detected at the chain layer too.
"""

from __future__ import annotations

import datetime as _dt
import hmac
import logging
from dataclasses import dataclass
from hashlib import sha256
from typing import Optional

# Re-use the LangGraph upgrade logger so chain verdicts land in the same
# audit stream as the AA1 / AA2 / AA9 / firewall events.
_logger = logging.getLogger("langgraph.upgrade")


# ---------------------------------------------------------------------------
# Public exception
# ---------------------------------------------------------------------------


class InterAgentMessageInvalid(Exception):
    """Raised by :meth:`AgentMessageChain.verify` when a signed message
    fails any of the three verification checks: MAC mismatch, non-monotonic
    sequence number, or chain-link mismatch.

    Attributes:
        reason: Stable, audit-grade rationale string. One of:
            ``"mac mismatch"``, ``"sequence not monotonic"``,
            ``"chain link mismatch"``, ``"malformed message"``.
            The reason is suitable for SIEM rules; the verifier never
            includes the offending payload or MAC bytes in the reason to
            avoid log injection.
    """

    def __init__(self, reason: str) -> None:
        super().__init__(reason)
        self.reason = reason


# ---------------------------------------------------------------------------
# Signed message — immutable carrier across LangGraph state
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SignedAgentMessage:
    """An inter-agent handoff payload with a chained HMAC-SHA256 signature.

    Frozen (immutable) so a consumer holding a reference cannot mutate
    ``payload`` or ``mac`` after the fact. Verification recomputes the MAC
    from the dataclass fields; if a caller deep-copies and mutates the copy,
    the verifier rejects it the same as any other tamper.

    Attributes:
        sender_role: The originating agent role (``"architect"``,
            ``"frontend"``, ``"backend"``, etc.). Bound into the MAC so a
            tampered role attribution is detected.
        sequence_num: Monotonic sequence number, starts at 1 for the first
            message in a session and increments by exactly 1 per
            :meth:`AgentMessageChain.sign` call. Bound into the MAC.
        payload: The actual handoff content. Arbitrary text (architecture
            JSON, generated code, review notes); the chain does not parse
            or interpret it. Bound into the MAC verbatim.
        mac: 32-byte HMAC-SHA256 over
            ``sender_role || ":" || sequence_num || ":" || payload || ":" || previous_mac``.
            Output of :meth:`hmac.HMAC.digest()` — raw bytes, not hex.
        previous_mac: The :attr:`mac` of the prior message in the chain, or
            ``b""`` for the first message of a session. Binds this message
            into the chain so reorderings and splices are detected.
        created_at_iso: UTC ISO-8601 timestamp recorded when
            :meth:`AgentMessageChain.sign` was called. **NOT** covered by
            the MAC — purely audit metadata. An attacker who tampers with
            ``created_at_iso`` cannot affect verification, which is the
            right trade-off: timestamps drift across producers in real
            distributed pipelines and we do not want a clock-skew bug to
            present as a security failure.
    """

    sender_role: str
    sequence_num: int
    payload: str
    mac: bytes
    previous_mac: bytes
    created_at_iso: str


# ---------------------------------------------------------------------------
# Session chain
# ---------------------------------------------------------------------------


def _mac_input(sender_role: str, sequence_num: int, payload: str, previous_mac: bytes) -> bytes:
    """Build the canonical MAC input.

    The exact concatenation is

        sender_role.encode("utf-8")
        + b":"
        + str(sequence_num).encode("ascii")
        + b":"
        + payload.encode("utf-8")
        + b":"
        + previous_mac

    The single-byte ``b":"`` delimiter binds the four fields without any
    ambiguity (the colon never appears inside ``sequence_num`` and the
    previous_mac is raw bytes appended after the final delimiter, so it
    cannot be confused with another field). UTF-8 is used for the
    variable-length text fields; ASCII for the integer (always a decimal
    string in ``[0-9]``).
    """
    return (
        sender_role.encode("utf-8")
        + b":"
        + str(sequence_num).encode("ascii")
        + b":"
        + payload.encode("utf-8")
        + b":"
        + previous_mac
    )


class AgentMessageChain:
    """Per-session signing + verification context for inter-agent handoffs.

    Each LangGraph run gets a fresh chain instance with a fresh 32-byte key
    (``secrets.token_bytes(32)``). The chain keeps two pieces of state:

      * ``_seq``: the *next* sequence number to issue when :meth:`sign` is
        called. Starts at ``0`` and increments to ``1`` on the first sign
        (so the first signed message has ``sequence_num == 1``).
      * ``_last_mac``: the MAC of the last signed message. Used as
        ``previous_mac`` for the next sign call.

    Verification keeps independent state:

      * ``_last_verified_seq``: the sequence number of the most recently
        verified message. The next verify must see ``msg.sequence_num >
        _last_verified_seq``.
      * ``_last_verified_mac``: the MAC of the most recently verified
        message. The next verify must see ``msg.previous_mac == _last_verified_mac``.

    Separate sign/verify state means a single chain instance can be used
    by the same process for both sides of the handoff (which is the
    realistic deployment — the builder owns the chain and dispatches to
    multiple agent nodes in-process). The two state pairs do not interfere.

    Note on threading: this class is **not** internally synchronized. The
    LangGraph pipeline executes nodes sequentially even when ``Send``
    parallel dispatch is enabled (the parallel branches converge through
    the ``aggregator`` reducer, which is the natural single sign-point for
    the merged output). If a future refactor introduces true concurrent
    signing on a single chain, wrap :meth:`sign` and :meth:`verify` in
    a ``threading.Lock``.
    """

    def __init__(self, session_key: bytes) -> None:
        """Initialize the chain with a fresh per-session key.

        Args:
            session_key: 32 bytes of cryptographically-random key material,
                typically ``secrets.token_bytes(32)``. Shorter keys are
                accepted (HMAC-SHA256 will zero-pad them to the block
                size) but the recommended length is the SHA-256 digest
                size (32 bytes) per RFC 2104 §3.

        Raises:
            TypeError: if ``session_key`` is not a :class:`bytes` instance.
            ValueError: if ``session_key`` is empty.
        """
        if not isinstance(session_key, (bytes, bytearray)):
            raise TypeError("session_key must be bytes; got " f"{type(session_key).__name__}")
        if len(session_key) == 0:
            raise ValueError("session_key must be non-empty")

        # Store a defensive copy as immutable bytes so the caller cannot
        # mutate the key after handing it to us.
        self._key: bytes = bytes(session_key)

        # Sign-side state — used by :meth:`sign`.
        self._seq: int = 0
        self._last_mac: bytes = b""

        # Verify-side state — used by :meth:`verify`. Independent of the
        # sign-side state by design (see class docstring).
        self._last_verified_seq: int = 0
        self._last_verified_mac: bytes = b""

    # ------------------------------------------------------------------
    # Sign
    # ------------------------------------------------------------------

    def sign(self, sender_role: str, payload: str) -> SignedAgentMessage:
        """Build and sign a new :class:`SignedAgentMessage`.

        Increments the sequence number, computes the HMAC over
        ``(role, seq, payload, previous_mac)``, updates the sign-side
        chain state, and returns the frozen message.

        Args:
            sender_role: The originating agent role.
            payload: The handoff content. Coerced via :func:`str` if the
                caller passes a non-string for defensive parity with the
                AA1/AA2 sanitizers — but the recommended contract is
                "always pass a real ``str``".

        Returns:
            A :class:`SignedAgentMessage` carrying the signature and the
            chain link.

        Raises:
            TypeError: if ``sender_role`` is not a string.
        """
        if not isinstance(sender_role, str):
            raise TypeError("sender_role must be str; got " f"{type(sender_role).__name__}")

        # Defensive payload coercion. We coerce rather than raise because
        # callers in ``multi_agent.py`` may pass an empty string, a JSON
        # serialization of a dict, or in the worst case ``None`` from a
        # node that returned no output. Failing closed on a non-str would
        # surface as a build-time crash; coercing keeps the chain alive
        # and the downstream verifier will see exactly what was signed.
        if not isinstance(payload, str):
            payload = "" if payload is None else str(payload)

        self._seq += 1
        seq = self._seq

        mac_input = _mac_input(sender_role, seq, payload, self._last_mac)
        digest = hmac.new(self._key, mac_input, sha256).digest()

        # ISO-8601 UTC, microsecond precision. NOT in the MAC input — see
        # the dataclass docstring.
        created_at_iso = _dt.datetime.now(_dt.timezone.utc).isoformat()

        msg = SignedAgentMessage(
            sender_role=sender_role,
            sequence_num=seq,
            payload=payload,
            mac=digest,
            previous_mac=self._last_mac,
            created_at_iso=created_at_iso,
        )

        # Advance sign-side state.
        self._last_mac = digest

        # Audit-grade log. We log the MAC's hex prefix (8 chars) for
        # forensic correlation across chain entries without leaking the
        # full MAC. We do NOT log the payload — it may contain sensitive
        # content (PII, API keys, etc.) that the AA9 layer would scrub
        # before egress; the chain layer should not undermine that.
        _logger.info(
            "[INTER_AGENT_CHAIN] sign role=%s seq=%d payload_len=%d mac=%s",
            sender_role,
            seq,
            len(payload),
            digest[:4].hex(),
        )

        return msg

    # ------------------------------------------------------------------
    # Verify
    # ------------------------------------------------------------------

    def verify(self, msg: SignedAgentMessage) -> bool:
        """Verify a :class:`SignedAgentMessage` against the chain.

        Three checks, in order:

          1. **Sequence monotonicity**:
             ``msg.sequence_num > self._last_verified_seq``.
          2. **Chain link**:
             ``msg.previous_mac == self._last_verified_mac``.
          3. **MAC match**: recompute the HMAC over ``(role, seq, payload,
             previous_mac)`` using the session key, and compare against
             ``msg.mac`` in constant time via :func:`hmac.compare_digest`.

        If all three pass, advance the verify-side chain state and return
        ``True``. If any fails, raise :class:`InterAgentMessageInvalid`
        with a stable rationale string. The verify-side state is *not*
        advanced on failure (a tampered message cannot poison the
        verifier).

        Args:
            msg: The signed message to verify. Typically pulled from the
                ``_provenance_record`` parallel field on the LangGraph
                state.

        Returns:
            ``True`` on success. (We never return ``False``; the failure
            path always raises so the caller cannot accidentally consume
            a tampered payload by forgetting to check the return value.)

        Raises:
            InterAgentMessageInvalid: on any verification failure. The
                ``reason`` attribute carries one of:
                ``"malformed message"``, ``"sequence not monotonic"``,
                ``"chain link mismatch"``, ``"mac mismatch"``.
        """
        # Structural / type checks. We fail closed on a malformed message
        # because it indicates a wire-level corruption that the chain
        # cannot meaningfully verify.
        if not isinstance(msg, SignedAgentMessage):
            self._reject("malformed message", "wrong type")
        if not isinstance(msg.sequence_num, int):
            self._reject("malformed message", "sequence_num not int")
        if not isinstance(msg.mac, (bytes, bytearray)):
            self._reject("malformed message", "mac not bytes")
        if not isinstance(msg.previous_mac, (bytes, bytearray)):
            self._reject("malformed message", "previous_mac not bytes")
        if not isinstance(msg.payload, str):
            self._reject("malformed message", "payload not str")
        if not isinstance(msg.sender_role, str):
            self._reject("malformed message", "sender_role not str")

        # 1. Sequence monotonicity.
        if msg.sequence_num <= self._last_verified_seq:
            self._reject(
                "sequence not monotonic",
                f"seq={msg.sequence_num} last={self._last_verified_seq}",
            )

        # 2. Chain link. Compared in constant time even though it's not
        # strictly required (the link bytes are not the secret); cheap
        # belt-and-braces in case the link is ever upgraded to a keyed
        # value in a future stage.
        if not hmac.compare_digest(bytes(msg.previous_mac), self._last_verified_mac):
            self._reject(
                "chain link mismatch",
                f"role={msg.sender_role} seq={msg.sequence_num}",
            )

        # 3. MAC match — constant-time compare via hmac.compare_digest.
        # NEVER use ``==`` here: a Python-level byte-by-byte equality
        # comparison can leak the matched-prefix length through timing
        # (CPython short-circuits on the first mismatching byte). The
        # stdlib function compares all bytes in constant time relative
        # to the lengths.
        expected = hmac.new(
            self._key,
            _mac_input(
                msg.sender_role,
                msg.sequence_num,
                msg.payload,
                bytes(msg.previous_mac),
            ),
            sha256,
        ).digest()
        if not hmac.compare_digest(expected, bytes(msg.mac)):
            self._reject(
                "mac mismatch",
                f"role={msg.sender_role} seq={msg.sequence_num}",
            )

        # All three checks passed — advance verify-side state and emit a
        # success log line for the audit channel.
        self._last_verified_seq = msg.sequence_num
        self._last_verified_mac = bytes(msg.mac)

        _logger.info(
            "[INTER_AGENT_CHAIN] verify OK role=%s seq=%d payload_len=%d mac=%s",
            msg.sender_role,
            msg.sequence_num,
            len(msg.payload),
            bytes(msg.mac)[:4].hex(),
        )
        return True

    # ------------------------------------------------------------------
    # Stateless verify — for fan-out consumers
    # ------------------------------------------------------------------

    def verify_signature(self, msg: SignedAgentMessage) -> bool:
        """Verify a message's MAC + structural fields WITHOUT touching
        the chain's verify-side state.

        Use this when multiple parallel consumers (LangGraph ``Send``
        branches — Frontend AND Backend) legitimately need to verify the
        SAME upstream emit. The stateful :meth:`verify` would reject the
        second call as a replay; ``verify_signature`` does not advance
        ``_last_verified_seq`` / ``_last_verified_mac`` and therefore can
        be called from N parallel consumers against the same message.

        Three checks:

          1. Structural / type checks on the dataclass fields.
          2. **MAC match**: recompute and ``hmac.compare_digest``.
          3. **No sequence regression OR chain replay across runs**: we
             require ``msg.sequence_num >= 1`` (positive integer) since
             this is the only weak ordering guarantee we can give without
             touching state. Stronger replay protection requires the
             stateful :meth:`verify`; parallel-branch callers must rely
             on the producer-side seq being monotonic (which it is —
             :meth:`sign` increments).

        Does NOT check chain-link or monotonicity — those are the
        guarantees the stateful :meth:`verify` adds on top.

        Raises:
            InterAgentMessageInvalid: on structural failure or MAC mismatch.
        """
        if not isinstance(msg, SignedAgentMessage):
            self._reject("malformed message", "wrong type")
        if not isinstance(msg.sequence_num, int) or msg.sequence_num < 1:
            self._reject("malformed message", "sequence_num invalid")
        if not isinstance(msg.mac, (bytes, bytearray)):
            self._reject("malformed message", "mac not bytes")
        if not isinstance(msg.previous_mac, (bytes, bytearray)):
            self._reject("malformed message", "previous_mac not bytes")
        if not isinstance(msg.payload, str):
            self._reject("malformed message", "payload not str")
        if not isinstance(msg.sender_role, str):
            self._reject("malformed message", "sender_role not str")

        expected = hmac.new(
            self._key,
            _mac_input(
                msg.sender_role,
                msg.sequence_num,
                msg.payload,
                bytes(msg.previous_mac),
            ),
            sha256,
        ).digest()
        if not hmac.compare_digest(expected, bytes(msg.mac)):
            self._reject(
                "mac mismatch",
                f"role={msg.sender_role} seq={msg.sequence_num}",
            )

        _logger.info(
            "[INTER_AGENT_CHAIN] verify_signature OK role=%s seq=%d " "payload_len=%d mac=%s",
            msg.sender_role,
            msg.sequence_num,
            len(msg.payload),
            bytes(msg.mac)[:4].hex(),
        )
        return True

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _reject(self, reason: str, detail: str) -> None:
        """Log a verify-side failure and raise :class:`InterAgentMessageInvalid`.

        Centralizing the rejection path means every failure follows the
        same audit format and the same exception shape. The ``detail``
        argument is logged but NOT included in the exception ``reason``
        attribute — the reason is stable for SIEM rules, detail is for
        operator diagnosis only.
        """
        _logger.warning(
            "[INTER_AGENT_CHAIN] verify REJECT reason=%s detail=%s " "last_seq=%d",
            reason,
            detail,
            self._last_verified_seq,
        )
        raise InterAgentMessageInvalid(reason)


# ---------------------------------------------------------------------------
# Convenience: provenance-record helpers for the parallel state field
# ---------------------------------------------------------------------------
# The conservative wiring (per the Day-7 spec) adds a ``_provenance_record``
# parallel field to the LangGraph state. The producer appends a
# ``SignedAgentMessage`` to that list; the consumer pops the latest entry
# and verifies it before reading the corresponding plain-text field.
#
# These helpers are stateless thin wrappers — they exist so callers in
# ``multi_agent.py`` can write a single line at the producer/consumer seam
# instead of repeating the list-append / list-tail / verify dance.


def append_provenance(state: dict, chain: AgentMessageChain, sender_role: str, payload: str) -> dict:
    """Sign ``payload`` under ``sender_role`` and append the signed message
    to ``state["_provenance_record"]``.

    Returns the same ``state`` dict (mutated in place) for chaining.
    Creates the ``_provenance_record`` list on first use.
    """
    record = state.get("_provenance_record")
    if not isinstance(record, list):
        record = []
        state["_provenance_record"] = record
    msg = chain.sign(sender_role, payload)
    record.append(msg)
    return state


def verify_latest_provenance(
    state: dict, chain: AgentMessageChain, expected_role: Optional[str] = None
) -> SignedAgentMessage:
    """Verify the most-recently-appended provenance record on ``state``.

    If ``expected_role`` is given, additionally require the latest
    message's ``sender_role`` to match — useful when a consumer wants to
    refuse if it was somehow handed a message from the wrong upstream
    node.

    Raises:
        InterAgentMessageInvalid: if the chain verify fails, the record is
            missing/empty, or ``expected_role`` does not match.
    """
    record = state.get("_provenance_record")
    if not isinstance(record, list) or not record:
        raise InterAgentMessageInvalid("malformed message")
    latest = record[-1]
    if expected_role is not None and latest.sender_role != expected_role:
        raise InterAgentMessageInvalid("malformed message")
    chain.verify(latest)
    return latest


__all__ = [
    "AgentMessageChain",
    "InterAgentMessageInvalid",
    "SignedAgentMessage",
    "append_provenance",
    "verify_latest_provenance",
]
