"""Generate legacy-compatible requirement entrypoints from one package catalog."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true');args=parser.parse_args()
    data=json.loads((ROOT/'dependencies/python-dependencies.json').read_text())
    stale=[]
    for target,profile in data['profiles'].items():
        content=('# Generated by scripts/sync_python_requirements.py; edit dependencies/python-dependencies.json.\n'
                 '# Dependency constraints are shared; profile membership is intentional.\n'
                 '-c '+profile['constraints']+'\n\n'+
                 '\n'.join(data['packages'][key] for key in sorted(profile['packages']))+'\n')
        path=ROOT/target
        if not path.exists() or path.read_text()!=content:
            stale.append(target)
            if not args.check:path.write_text(content)
    if args.check and stale:raise SystemExit('Outdated generated requirements: '+', '.join(stale))
    print('Checked' if args.check else 'Generated',len(data['profiles']),'Python requirement profiles')
if __name__=='__main__':main()
