"""
Phase 26 — policy transparency Merkle attestation proofs (Gap G3).
==================================================================

Exercises the REAL ``PolicyTransparencyLedger`` (RFC-6962 SHA-256 Merkle log)
and the REAL ``/api/v1/transparency/proof`` endpoint end to end:

  TC1  valid event  -> proof validates cryptographically against the signed root
  TC2  unknown id   -> HTTP 404 (exact)
  TC3  one flipped byte (audit path OR leaf) -> verification fails hard
  + the live policy->transparency feed records a real leaf when flag is ON
  + an anti-divergence cross-check: the vendored RFC-6962 functions are
    byte-identical to the infra/security/rekor_v2_log.py originals.

Anti-gaming (charter §II): fixed-value asserts (== 404, is True / is False);
the proof is generated by the REAL ledger (not a stub), validated by the REAL
RFC-6962 verifier + REAL ECDSA-P256 STH signature, and the tamper test flips a
genuine byte rather than asserting a mocked failure.

Run: .venv_p312/bin/python -m pytest tests/audit/test_phase26_attestation_proofs.py -n 0
"""

from __future__ import annotations

import base64
import copy

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from services.policy_transparency import (
    PolicyTransparencyLedger,
    _reset_singleton_for_tests,
    verify_inclusion,
    verify_proof,
)


@pytest.fixture
def ledger(tmp_path):
    """A ledger bound to a tmp JSONL, installed as the process singleton so the
    endpoint and the policy-feed both hit it. Reset afterward."""
    lg = PolicyTransparencyLedger(path=str(tmp_path / "policy_transparency.jsonl"))
    _reset_singleton_for_tests(lg)
    yield lg
    _reset_singleton_for_tests(None)


def _client() -> TestClient:
    from api import transparency_routes
    from api.deps import get_current_user

    app = FastAPI()
    app.include_router(transparency_routes.router, prefix="/api")

    class _U:
        id = "test-user"

    app.dependency_overrides[get_current_user] = lambda: _U()
    return TestClient(app, raise_server_exceptions=False)


# ---------------------------------------------------------------------------
# TC1 — valid event -> proof validates against the active signed root
# ---------------------------------------------------------------------------


def test_tc1_valid_event_proof_validates(ledger):
    # Append a few events so the tree has interior nodes (non-trivial path).
    ledger.record(
        event_type="regional_policy_enforcement",
        schema_hash="a" * 64,
        metadata={"action": "global"},
    )
    target = ledger.record(
        event_type="eu_local_enforcement",
        schema_hash="b" * 64,
        metadata={"action": "local", "user_id": "u1"},
    )
    ledger.record(
        event_type="regional_policy_enforcement",
        schema_hash="c" * 64,
        metadata={"action": "denied"},
    )

    r = _client().get(
        "/api/v1/transparency/proof", params={"event_id": target["event_id"]}
    )
    assert r.status_code == 200
    proof = r.json()

    # Full client-side verification (inclusion path + ECDSA-P256 STH over root).
    assert verify_proof(proof) is True

    # And the raw RFC-6962 inclusion check against the active root, explicitly.
    payload = base64.b64decode(proof["leaf_payload_b64"])
    assert (
        verify_inclusion(
            leaf_data=payload,
            leaf_index=proof["leaf_index"],
            tree_size=proof["tree_size"],
            audit_path=[bytes.fromhex(h) for h in proof["audit_path"]],
            expected_root=bytes.fromhex(proof["root_hash"]),
        )
        is True
    )
    # The proof's root is the ledger's current active root (no stale snapshot).
    assert proof["root_hash"] == ledger.latest_root()


# ---------------------------------------------------------------------------
# TC2 — unknown event id -> exactly 404
# ---------------------------------------------------------------------------


def test_tc2_unknown_event_id_returns_exactly_404(ledger):
    ledger.record(
        event_type="regional_policy_enforcement",
        schema_hash="a" * 64,
        metadata={"action": "global"},
    )
    r = _client().get(
        "/api/v1/transparency/proof", params={"event_id": "pte_999_deadbeefdeadbeef"}
    )
    assert r.status_code == 404


# ---------------------------------------------------------------------------
# TC3 — single-byte tamper of audit path OR leaf -> verification fails hard
# ---------------------------------------------------------------------------


def test_tc3_tampered_audit_path_byte_fails(ledger):
    for i in range(5):
        rec = ledger.record(
            event_type="regional_policy_enforcement",
            schema_hash="d" * 64,
            metadata={"n": i},
        )
        if i == 2:
            target = rec
    proof = ledger.generate_proof(target["event_id"])
    assert verify_proof(proof) is True  # baseline: untampered passes

    # Flip one byte of the first audit-path node.
    tampered = copy.deepcopy(proof)
    h0 = bytearray(bytes.fromhex(tampered["audit_path"][0]))
    h0[0] ^= 0x01
    tampered["audit_path"][0] = h0.hex()
    assert verify_proof(tampered) is False


def test_tc3_tampered_leaf_byte_fails(ledger):
    for i in range(5):
        rec = ledger.record(
            event_type="eu_local_enforcement", schema_hash="e" * 64, metadata={"n": i}
        )
        if i == 1:
            target = rec
    proof = ledger.generate_proof(target["event_id"])
    assert verify_proof(proof) is True

    # Flip one byte of the leaf payload.
    tampered = copy.deepcopy(proof)
    raw = bytearray(base64.b64decode(tampered["leaf_payload_b64"]))
    raw[0] ^= 0x01
    tampered["leaf_payload_b64"] = base64.b64encode(bytes(raw)).decode("ascii")
    assert verify_proof(tampered) is False


def test_tc3_forged_root_fails_sth(ledger):
    # A structurally-valid inclusion path against a DIFFERENT (forged) root must
    # fail the STH signature check even if inclusion alone might be coerced.
    ledger.record(event_type="x", schema_hash="f" * 64, metadata={})
    target = ledger.record(event_type="y", schema_hash="0" * 64, metadata={})
    proof = ledger.generate_proof(target["event_id"])
    tampered = copy.deepcopy(proof)
    root = bytearray(bytes.fromhex(tampered["root_hash"]))
    root[0] ^= 0x01
    tampered["root_hash"] = root.hex()
    assert verify_proof(tampered) is False


# ---------------------------------------------------------------------------
# Live policy -> transparency feed (flag-gated) records a real leaf
# ---------------------------------------------------------------------------


def test_policy_feed_records_when_flag_on(ledger, monkeypatch):
    monkeypatch.setenv("VOS3_POLICY_TRANSPARENCY_ENABLED", "1")
    from services import regional_policy as rp

    before = ledger.tree_size()
    decision = rp.classify_zone("DE", consent_to_global=False)
    # enforce_routing logs + feeds; DE w/o consent + no local lane -> denial,
    # but the AUDIT FEED fires on every branch (including denial).
    with pytest.raises(rp.ComplianceDenied):
        rp.enforce_routing(decision, user_id_for_log="clerk_abc")
    assert ledger.tree_size() == before + 1

    # The freshly-fed event is provable end to end.
    last_id = ledger._records[-1]["event_id"]  # noqa: SLF001 (test introspection)
    proof = ledger.generate_proof(last_id)
    assert verify_proof(proof) is True


def test_policy_feed_noop_when_flag_off(ledger, monkeypatch):
    monkeypatch.delenv("VOS3_POLICY_TRANSPARENCY_ENABLED", raising=False)
    from services import regional_policy as rp

    before = ledger.tree_size()
    decision = rp.classify_zone("US", consent_to_global=False)
    rp.enforce_routing(decision, user_id_for_log="clerk_us")  # "global", no raise
    assert ledger.tree_size() == before  # flag OFF -> no leaf written


# ---------------------------------------------------------------------------
# Anti-divergence: vendored RFC-6962 funcs == infra/security originals
# ---------------------------------------------------------------------------


def test_vendored_merkle_matches_infra_original():
    import os
    import sys

    repo_root = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "..", "..")
    )
    if repo_root not in sys.path:
        sys.path.insert(0, repo_root)
    try:
        from infra.security import rekor_v2_log as orig
    except Exception:  # pragma: no cover - infra not importable in this env
        pytest.skip("infra.security.rekor_v2_log not importable in this environment")

    from services import policy_transparency as vend

    leaves_data = [b"", b"a"] + [b"policy-event-%d" % i for i in range(13)]
    leaves = [vend.leaf_hash(d) for d in leaves_data]
    orig_leaves = [orig.leaf_hash(d) for d in leaves_data]
    assert leaves == orig_leaves

    assert vend.compute_root(leaves) == orig.compute_root(orig_leaves)
    for idx in range(len(leaves)):
        assert vend.compute_inclusion_path(leaves, idx) == orig.compute_inclusion_path(
            orig_leaves, idx
        )
        path = vend.compute_inclusion_path(leaves, idx)
        assert (
            vend.verify_inclusion(
                leaf_data=leaves_data[idx],
                leaf_index=idx,
                tree_size=len(leaves),
                audit_path=path,
                expected_root=vend.compute_root(leaves),
            )
            is True
        )
