// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 VOS3 Project
//
// AUTO-GENERATED by tools/schema/sync_types.py — DO NOT EDIT BY HAND.
//
// Source of truth: backend/api/*_routes.py Pydantic BaseModel definitions.
// Regenerate after Pydantic schema changes:
//     python3 tools/schema/sync_types.py
//
// Schema-sync gap closure per
// docs/audit/300_INTEGRATION_FAILURES_REPORT.md §5.1.

// ----- backend/api/agents_routes.py -----

export interface VoiceSettings {
  stability?: number;
  similarity_boost?: number;
  style?: number;
  speaker_boost?: boolean;
}

export interface AgentConfig {
  name: string;
  role: string;
  model?: (string) | null;
  model_category?: (string) | null;
  category?: (string) | null;
  platform_tag?: (string) | null;
  system_prompt?: (string) | null;
  services?: (string)[];
  temperature?: number;
  max_tokens?: (number) | null;
  template_id?: (string) | null;
  description?: (string) | null;
  voice_id?: (string) | null;
  voice_settings?: (VoiceSettings) | null;
}

export interface Agent {
  id: string;
  name: string;
  role: string;
  model: string;
  model_category?: (string) | null;
  category?: (string) | null;
  platform_tag?: (string) | null;
  system_prompt: (string) | null;
  services?: (string)[];
  temperature: number;
  status: string;
  created_at: string;
  last_run?: (string) | null;
  run_count?: number;
  template_id?: (string) | null;
  description?: (string) | null;
  voice_id?: (string) | null;
  voice_settings?: (VoiceSettings) | null;
}

export interface AgentTask {
  task: string;
  context?: (Record<string, any>) | null;
  timeout?: (number) | null;
}

export interface AgentLog {
  id: string;
  agent_id: string;
  timestamp: string;
  level: string;
  message: string;
  tokens?: (number) | null;
  cost?: (number) | null;
  duration_ms?: (number) | null;
}

export interface TaskResult {
  success: boolean;
  result: any;
  error?: (string) | null;
  tokens_used: number;
  cost: number;
  duration_ms: number;
}

export interface OrchestrationRequest {
  task: string;
  agents?: ((string)[]) | null;
  mode?: string;
}

export interface TTSRequest {
  text: string;
  voice_id?: (string) | null;
}

export interface AgentMemoryRequest {
  content: string;
  memory_type?: string;
  session_id?: (string) | null;
}

export interface AgentRecallRequest {
  query: string;
  top_k?: number;
}

export interface TruthEntry {
  fact: string;
  source?: (string) | null;
  confidence?: number;
}

// ----- backend/api/aiva_routes.py -----

export interface CreateFromDescriptionRequest {
  description: string;
  organization_id?: (string) | null;
}

export interface CreateFromTemplateRequest {
  agent_type: string;
}

export interface SetArchitectureRequest {
  architecture: string;
}

export interface SetToolsRequest {
  tool_ids?: (string)[];
}

export interface ConfigureSecurityRequest {
  require_approval_for?: (string)[];
  blocked_topics?: (string)[];
  pii_redaction?: boolean;
  max_actions_per_minute?: number;
  human_in_loop_threshold?: number;
  audit_all_actions?: boolean;
}

export interface SetModeRequest {
  mode: string;
}

export interface TestAgentRequest {
  message: string;
}

export interface AddEscalationRuleRequest {
  condition: string;
  action?: string;
  target?: string;
  priority?: string;
}

export interface UpdateAgentRequest {
  name?: (string) | null;
  description?: (string) | null;
  mode?: (string) | null;
  temperature?: (number) | null;
  system_prompt?: (string) | null;
}

// ----- backend/api/analytics_routes.py -----

export interface TrackEventRequest {
  event_type: string;
  properties?: Record<string, any>;
  page_url?: (string) | null;
  referrer?: (string) | null;
  session_id?: (string) | null;
  project_id?: (string) | null;
}

export interface TrackPageViewRequest {
  page_url: string;
  referrer?: (string) | null;
  session_id?: (string) | null;
}

export interface TrackAIGenerationRequest {
  project_id?: (string) | null;
  prompt_tokens?: number;
  completion_tokens?: number;
  model?: string;
  duration_ms?: number;
  success?: boolean;
}

export interface FunnelRequest {
  steps: (string)[];
  days?: number;
}

export interface DashboardResponse {
  total_users: number;
  active_users_today: number;
  active_users_week: number;
  active_users_month: number;
  new_users_today: number;
  new_users_week: number;
  total_projects: number;
  projects_created_today: number;
  projects_created_week: number;
  total_ai_generations: number;
  ai_generations_today: number;
  total_tokens_used: number;
  tokens_used_today: number;
  total_deployments: number;
  deployments_today: number;
  deployment_success_rate: number;
  errors_today: number;
  error_rate: number;
  avg_response_time: number;
  p99_response_time: number;
}

export interface TimeSeriesPoint {
  date: string;
  count: number;
}

export interface TopPage {
  page: string;
  views: number;
}

export interface AIUsageStats {
  total_generations: number;
  successful: number;
  failed: number;
  success_rate: number;
  total_tokens: number;
  avg_tokens_per_generation: number;
  total_duration_ms: number;
  avg_duration_ms: number;
  by_model: Record<string, any>;
}

export interface FunnelStep {
  step: string;
  step_number: number;
  users: number;
  conversion_rate: number;
}

export interface UserAnalytics {
  user_id: string;
  total_sessions: number;
  total_page_views: number;
  total_actions: number;
  total_prompts: number;
  total_tokens_used: number;
  total_projects: number;
  total_deployments: number;
  first_seen: (string) | null;
  last_seen: (string) | null;
}

// ----- backend/api/app_api_routes.py -----

export interface CreateRecordRequest {
  entityId: string;
  data: Record<string, any>;
}

export interface ExecuteWorkflowRequest {
  input?: (Record<string, any>) | null;
}

export interface AIGenerateRequest {
  prompt: string;
  model?: (string) | null;
  maxTokens?: (number) | null;
}

export interface WriteFileRequest {
  path: string;
  content: string;
}

// ----- backend/api/app_auth_routes.py -----

export interface AuthorizeRequest {
  app_id: string;
  redirect_uri: string;
  scopes: (string)[];
  state?: (string) | null;
}

export interface AuthorizeResponse {
  consent_url?: (string) | null;
  scopes: (Record<string, any>)[];
  app_id: string;
}

export interface ConsentGrantRequest {
  app_id: string;
  granted_scopes: (string)[];
  user_id: string;
  organization_id: string;
}

export interface ConsentGrantResponse {
  access_token: string;
  token_type?: string;
  scopes: (string)[];
  expires_in?: number;
}

// ----- backend/api/app_submission_routes.py -----

export interface AppSubmission {
  app_id: string;
  version: string;
  changelog: string;
  manifest: Record<string, any>;
  developer_id: string;
}

export interface SubmissionResponse {
  submission_id: string;
  status: string;
  message: string;
}

// ----- backend/api/auth_setup_routes.py -----

export interface AuthSetupRequest {
  project_id: string;
  enabled: boolean;
  providers?: (string)[];
}

export interface AuthSetupResponse {
  enabled: boolean;
  files_generated: number;
}

// ----- backend/api/billing_routes.py -----

export interface CreateCheckoutRequest {
  plan?: string;
  interval?: string;
  success_url?: (string) | null;
  cancel_url?: (string) | null;
}

export interface CreateTokenCheckoutRequest {
  package: string;
  success_url?: (string) | null;
  cancel_url?: (string) | null;
}

export interface PortalSessionRequest {
  return_url?: (string) | null;
}

export interface UseCreditsRequest {
  amount: number;
  reason?: string;
  reference_id?: (string) | null;
}

export interface AddCreditsRequest {
  user_id: string;
  amount: number;
  reason?: string;
  transaction_type?: string;
}

export interface RefundCreditsRequest {
  amount: number;
  reason?: string;
  reference_id?: (string) | null;
}

// ----- backend/api/blueprints_routes.py -----

export interface DeployRequest {
  blueprint_id: string;
  customizations?: Record<string, any>;
}

export interface UpdateDeploymentRequest {
  enabled_agents?: ((string)[]) | null;
  enabled_workflows?: ((string)[]) | null;
  customizations?: (Record<string, any>) | null;
  status?: (string) | null;
}

// ----- backend/api/bmad_routes.py -----

export interface CreateSessionRequest {
  project_name?: string;
  description?: string;
  mode?: string;
  git_repo?: (string) | null;
  auto_commit?: boolean;
  metadata?: Record<string, any>;
}

export interface StartWorkflowRequest {
  user_input?: string;
}

export interface AdvancePhaseRequest {
  to_phase?: (string) | null;
}

export interface ApprovalRequest {
  approved: boolean;
  feedback?: (string) | null;
}

export interface GitCommitRequest {
  message?: string;
  files?: (string)[];
}

// (duplicate of DeployRequest from earlier file — skipped)

export interface QuickModeRequest {
  description?: string;
  project_name?: string;
}

export interface UpdateSessionRequest {
  project_name?: (string) | null;
  description?: (string) | null;
}

export interface CloneSessionRequest {
  project_name?: string;
  description?: (string) | null;
}

export interface SessionResponse {
  id: string;
  project_name: string;
  description: string;
  mode: string;
  current_phase: string;
  phases: Record<string, Record<string, any>>;
  artifacts_count: number;
  pending_approvals: number;
  git_enabled: boolean;
  is_active: boolean;
  deployment_url: (string) | null;
  created_at: string;
  updated_at: string;
}

// ----- backend/api/chat_routes.py -----

export interface ChatMessage {
  role: string;
  content?: string;
}

export interface ChatRequest {
  messages?: (ChatMessage)[];
  model?: (string) | null;
  stream?: boolean;
  temperature?: number;
  max_tokens?: (number) | null;
}

export interface ChatResponse {
  message: ChatMessage;
  model: string;
  provider: string;
  tokens_used: number;
  cost: number;
  cached: boolean;
}

export interface ModelInfo {
  id: string;
  provider: string;
  cost_per_1k_input: number;
  cost_per_1k_output: number;
  max_context: number;
  description: string;
}

export interface SummarizeMessage {
  role: string;
  content: string;
  agent_name?: (string) | null;
}

export interface SummarizeRequest {
  messages: (SummarizeMessage)[];
  session_type?: string;
  session_id: string;
  agent_ids?: (string)[];
  agent_names?: (string)[];
  topic_hint?: (string) | null;
}

// ----- backend/api/checkpoint_routes.py -----

export interface CheckpointResponse {
  id: string;
  description: string;
  created_at: string;
}

export interface CheckpointListResponse {
  checkpoints: (CheckpointResponse)[];
}

export interface CreateCheckpointRequest {
  description?: string;
}

// ----- backend/api/clerk_webhook.py -----

export interface ClerkUserData {
  id: string;
  email_addresses: (Record<string, any>)[];
  first_name?: (string) | null;
  last_name?: (string) | null;
  image_url?: (string) | null;
  created_at?: (number) | null;
  updated_at?: (number) | null;
  public_metadata?: Record<string, any>;
  private_metadata?: Record<string, any>;
}

export interface ClerkWebhookEvent {
  type: string;
  data: Record<string, any>;
  object?: string;
}

// ----- backend/api/codegen_routes.py -----

export interface GenerateRequest {
  prompt: string;
  language: string;
  framework?: (string) | null;
  context?: (string) | null;
}

export interface GeneratedFile {
  path: string;
  content: string;
  language: string;
}

export interface ValidationResult {
  valid: boolean;
  errors: (string)[];
  warnings: (string)[];
}

export interface GenerateResponse {
  code: string;
  language: string;
  explanation: string;
  dependencies: (string)[];
  validation: ValidationResult;
}

export interface ProjectRequest {
  prompt: string;
  project_type?: (string) | null;
  language?: (string) | null;
  features?: ((string)[]) | null;
}

export interface ProjectResponse {
  name: string;
  description: string;
  files: (GeneratedFile)[];
  dependencies: Record<string, any>;
  setup_instructions: string;
}

export interface OSFeatureRequest {
  spec?: string;
  max_iterations?: number;
}

export interface OSReviewIssue {
  type: string;
  location: string;
  severity: string;
  description: string;
  fix?: (string) | null;
}

export interface OSReviewResult {
  passed: boolean;
  issues?: (OSReviewIssue)[];
  suggestions?: (string)[];
  security_implications?: (string)[];
}

export interface OSFuzzTestCase {
  name: string;
  input_type: string;
  input_value: string;
  expected_behavior: string;
  rationale: string;
}

export interface OSFuzzResult {
  test_cases?: (OSFuzzTestCase)[];
  crash_scenarios?: (Record<string, any>)[];
  edge_cases_covered?: (string)[];
  recommendations?: (string)[];
}

export interface OSFeatureResponse {
  architecture: string;
  memory_map: string;
  code: string;
  review: OSReviewResult;
  fuzz_results: OSFuzzResult;
  formal_proofs: Record<string, any>;
  iterations: number;
  pipeline_info: Record<string, any>;
}

export interface OSPipelineInfoResponse {
  name: string;
  version: string;
  stages: (Record<string, any>)[];
  warnings: (string)[];
}

// ----- backend/api/collab_routes.py -----

export interface InviteRequest {
  project_id: string;
  email: string;
  role?: string;
}

// ----- backend/api/database_routes.py -----

export interface ColumnDef {
  id: string;
  name: string;
  type: string;
}

export interface TableDef {
  name: string;
  columns: (ColumnDef)[];
}

// (duplicate of GenerateRequest from earlier file — skipped)

// (duplicate of GenerateResponse from earlier file — skipped)

// ----- backend/api/deploy_routes.py -----

// (duplicate of DeployRequest from earlier file — skipped)

export interface DeployResponse {
  deployment_id: string;
  url: string;
  status: string;
}

// ----- backend/api/design_system_routes.py -----

export interface FigmaImportRequest {
  tokens: Record<string, any>;
}

export interface GenerateCSSRequest {
  mode?: string;
}

// ----- backend/api/developer_routes.py -----

export interface DeveloperRegisterRequest {
  display_name: string;
  email: string;
  website?: (string) | null;
  bio?: (string) | null;
}

export interface DeveloperResponse {
  id: string;
  display_name: string;
  email: string;
  website?: (string) | null;
  bio?: (string) | null;
  verified?: boolean;
  total_apps?: number;
  total_earnings?: number;
}

// ----- backend/api/edit_routes.py -----

export interface EditRequest {
  project_id: string;
  instruction: string;
}

export interface EditResponse {
  message: string;
  updated_files: Record<string, string>;
}

// ----- backend/api/expert_routes.py -----

export interface CreateExpertRequestBody {
  project_id: string;
  description?: string;
  build_state?: (Record<string, any>) | null;
}

export interface ResolveRequestBody {
  patches?: Record<string, string>;
  summary?: string;
}

// ----- backend/api/feature_flag_routes.py -----

export interface UpsertFlagRequest {
  enabled?: (boolean) | null;
  rollout_pct?: (number) | null;
  description?: (string) | null;
  metadata?: (Record<string, any>) | null;
}

export interface EvaluateFlagRequest {
  flag_name: string;
  user_id?: (string) | null;
}

// ----- backend/api/figma_routes.py -----

export interface FetchFramesRequest {
  url: string;
}

export interface FrameResponse {
  id: string;
  name: string;
  thumbnail: string;
}

export interface ConvertRequest {
  project_id: string;
  url: string;
  frame_ids: (string)[];
}

// ----- backend/api/files.py -----

export interface RenameRequest {
  old_path?: string;
  new_path?: string;
}

export interface MkdirRequest {
  path?: string;
}

export interface CreateFileRequest {
  path?: string;
  content?: string;
  overwrite?: boolean;
}

// ----- backend/api/gateway_routes.py -----

export interface InferenceRequest {
  slot_id?: number;
  prompt?: string;
  max_tokens?: number;
  temperature?: number;
}

export interface ProvenanceModel {
  hmac_hex: string;
  node_id: string;
  slot_id: number;
  timestamp: number;
  chain_hash: string;
}

export interface InferenceResponse {
  text: string;
  tokens_generated: number;
  latency_us: number;
  provenance: ProvenanceModel;
}

export interface QuotaResponse {
  allowed: boolean;
  remaining_tokens: number;
  tier: string;
  reset_at: number;
  daily_limit: number;
}

export interface SlotInfo {
  slot_id: number;
  status: string;
  raw?: (string) | null;
  error?: (string) | null;
}

export interface SlotsResponse {
  slots: (SlotInfo)[];
  total: number;
}

export interface VerifyRequest {
  response_body?: string;
  provenance_header?: ProvenanceModel;
}

export interface VerifyResponse {
  valid: boolean;
  details: Record<string, any>;
}

// ----- backend/api/github_sync_routes.py -----

export interface ExportToGitHubRequest {
  repo_name?: string;
  branch?: string;
  files: Record<string, string>;
  commit_message?: (string) | null;
  version_prefix?: (string) | null;
  create_repo?: boolean;
}

export interface SyncBranchRequest {
  repo_name: string;
  source_branch?: string;
  target_branch?: string;
  files: Record<string, string>;
}

export interface CreateVersionRequest {
  repo_name: string;
  version?: string;
  base_branch?: string;
}

export interface FreezeFileRequest {
  path: string;
  reason?: (string) | null;
  lock_ai?: boolean;
}

export interface CreatePRRequest {
  repo_name: string;
  title: string;
  head: string;
  base?: string;
  body?: (string) | null;
}

export interface SyncResultResponse {
  status: string;
  commit_sha: (string) | null;
  branch: (string) | null;
  url: (string) | null;
  files_synced: (string)[];
  conflicts: (string)[];
  message: string;
}

export interface FileLockResponse {
  path: string;
  status: string;
  locked_by: string;
  locked_at: string;
  reason: (string) | null;
}

// ----- backend/api/inbox_routes.py -----

export interface CreateConversationRequest {
  contact_id: string;
  channel: string;
  subject?: string;
}

export interface SendMessageRequest {
  content: string;
  attachments?: (Record<string, any>)[];
}

export interface UpdateConversationRequest {
  status?: (string) | null;
  priority?: (string) | null;
  assigned_to?: (string) | null;
  tags?: ((string)[]) | null;
}

export interface CreateContactRequest {
  name: string;
  email?: (string) | null;
  phone?: (string) | null;
  company?: (string) | null;
  title?: (string) | null;
  tags?: (string)[];
  notes?: string;
}

export interface CreateQuickReplyRequest {
  name: string;
  content: string;
  category?: string;
  shortcut?: (string) | null;
  channel?: (string) | null;
}

// ----- backend/api/kernel_routes.py -----

export interface WriteRequest {
  path?: string;
  content?: string;
}

export interface ExecRequest {
  path?: string;
  args?: string;
}

// (duplicate of RenameRequest from earlier file — skipped)

export interface CompileAndRunRequest {
  source_code?: string;
  program_name?: string;
  args?: string;
}

export interface AppLoadRequest {
  app_id?: number;
  binary_path?: string;
}

// ----- backend/api/marketplace_routes.py -----

export interface InstallRequest {
  project_id: string;
  component_id: string;
}

// ----- backend/api/memory_routes.py -----

export interface StoreMemoryRequest {
  content: string;
  memory_type?: string;
  metadata?: (Record<string, any>) | null;
  auto_tag?: boolean;
}

export interface AddMemoryRequest {
  content: string;
  memory_type?: string;
  metadata?: (Record<string, any>) | null;
  auto_tag?: boolean;
}

export interface QueryMemoryRequest {
  query: string;
  top_k?: number;
  memory_type?: (string) | null;
  min_relevance?: number;
}

export interface UpdateInsightRequest {
  content?: (string) | null;
  memory_type?: (string) | null;
  metadata?: (Record<string, any>) | null;
  tags?: ((string)[]) | null;
}

export interface BulkDeleteRequest {
  ids: (string)[];
}

export interface ImportRequest {
  insights: (Record<string, any>)[];
}

// ----- backend/api/model_routes.py -----

export interface DownloadRequest {
  url?: string;
  model_id?: string;
  expected_sha256?: (string) | null;
  label?: (string) | null;
}

export interface ModelResponse {
  model_id: string;
  filename: string;
  format_id: number;
  quant_label: string;
  total_size: number;
  sha256: string;
  source_url: string;
  downloaded_at: number;
  label: string;
  verified: boolean;
  active: boolean;
  slot_id: (number) | null;
  kernel_mapped_at?: (number) | null;
  kernel_base_addr?: (string) | null;
  kernel_xxh3?: (string) | null;
  kernel_crc32c?: (string) | null;
  kernel_latency_ms?: (number) | null;
}

export interface ActivateRequest {
  slot_id?: number;
}

export interface ActivateResponse {
  model_id: string;
  slot_id: number;
  base_addr: string;
  size: number;
  xxh3: string;
  crc32c: string;
  elapsed_ms: number;
  warp: boolean;
  hall_assigned: boolean;
}

// ----- backend/api/native_deploy_routes.py -----

export interface NativeDeployRequest {
  project_id: string;
  app_name?: (string) | null;
  manifest_override?: (Record<string, any>) | null;
}

// ----- backend/api/payment_routes.py -----

export interface ProductDef {
  id: string;
  name: string;
  price: string;
  description?: string;
  recurring?: boolean;
  interval?: string;
}

export interface PaymentSetupRequest {
  project_id: string;
  products: (ProductDef)[];
  stripe_connected?: boolean;
}

export interface PaymentSetupResponse {
  files_generated: number;
}

// ----- backend/api/plugin_routes.py -----

export interface PluginManifestRequest {
  id: string;
  name: string;
  version: string;
  description?: string;
  author?: string;
  type?: string;
  main?: string;
  dependencies?: (string)[];
  python_dependencies?: (string)[];
  permissions?: (string)[];
  config_schema?: Record<string, any>;
  hooks?: (string)[];
}

export interface PluginConfigRequest {
  settings?: Record<string, any>;
  enabled?: boolean;
}

export interface ExecuteHookRequest {
  hook_type: string;
  data?: Record<string, any>;
  project_id?: (string) | null;
}

export interface PluginResponse {
  id: string;
  name: string;
  version: string;
  description: string;
  author: string;
  type: string;
  status: string;
  enabled: boolean;
  loaded_at: (string) | null;
  error: (string) | null;
  config: (Record<string, any>) | null;
  permissions: (string)[];
  hooks: (string)[];
}

export interface PluginListResponse {
  plugins: (PluginResponse)[];
  total: number;
}

export interface HookResultResponse {
  plugin_id: string;
  success: boolean;
  data: (Record<string, any>) | null;
  error: (string) | null;
  duration_ms: number;
}

export interface ExecuteHookResponse {
  hook_type: string;
  results: (HookResultResponse)[];
  total_duration_ms: number;
}

export interface MarketplacePlugin {
  id: string;
  name: string;
  version: string;
  description: string;
  author: string;
  type: string;
  category: string;
  tags: (string)[];
  downloads: number;
  rating: number;
  price: number;
  icon: (string) | null;
  homepage: (string) | null;
}

// ----- backend/api/proactive_routes.py -----

export interface ActionRequest {
  action_id: string;
}

// ----- backend/api/project_routes.py -----

export interface ProjectCreateRequest {
  name?: (string) | null;
  description: string;
  category: string;
  template_id?: (string) | null;
}

// (duplicate of ProjectResponse from earlier file — skipped)

export interface ProjectListResponse {
  projects: (ProjectResponse)[];
}

// ----- backend/api/prompt_routes.py -----

export interface CreatePromptRequest {
  input_prompt: string;
  prompt_type?: string;
  project_id?: (string) | null;
  session_id?: (string) | null;
  model?: (string) | null;
  provider?: (string) | null;
  tags?: (string)[];
}

export interface UpdatePromptRequest {
  status?: (string) | null;
  output_response?: (string) | null;
  tags?: ((string)[]) | null;
}

export interface RatePromptRequest {
  rating: number;
  feedback?: (string) | null;
}

export interface AddTagsRequest {
  tags: (string)[];
}

// ----- backend/api/response.py -----

export interface ApiResponse {
  status?: string;
  data?: (any) | null;
  error?: (string) | null;
}

// ----- backend/api/settings_routes.py -----

export interface ApiKeysRequest {
  openai_api_key?: (string) | null;
  anthropic_api_key?: (string) | null;
  google_api_key?: (string) | null;
  tavily_api_key?: (string) | null;
  github_token?: (string) | null;
}

export interface ApiKeyStatus {
  configured: boolean;
  masked_key?: (string) | null;
}

export interface ConfigStatus {
  openai: ApiKeyStatus;
  anthropic: ApiKeyStatus;
  google: ApiKeyStatus;
  tavily: ApiKeyStatus;
  github: ApiKeyStatus;
  redis_url?: (string) | null;
  ollama_url?: (string) | null;
}

export interface CreateRepoRequest {
  name: string;
  description?: (string) | null;
  private?: boolean;
}

export interface ActivateModelRequest {
  model_id: string;
  api_key?: (string) | null;
}

// (duplicate of ModelResponse from earlier file — skipped)

// ----- backend/api/team_routes.py -----

export interface CreateTeamRequest {
  name: string;
  description?: (string) | null;
  logo_url?: (string) | null;
}

export interface UpdateTeamRequest {
  name?: (string) | null;
  description?: (string) | null;
  logo_url?: (string) | null;
  website?: (string) | null;
}

export interface InviteMemberRequest {
  email: string;
  role?: string;
}

export interface UpdateRoleRequest {
  role: string;
}

export interface ShareProjectRequest {
  project_id: string;
  permission?: string;
  team_id?: (string) | null;
  user_id?: (string) | null;
}

export interface TeamResponse {
  id: string;
  name: string;
  slug: string;
  owner_id: string;
  description: (string) | null;
  logo_url: (string) | null;
  website: (string) | null;
  max_members: number;
  max_projects: number;
  member_count: number;
  project_count: number;
  created_at: string;
}

export interface MemberResponse {
  user_id: string;
  team_id: string;
  role: string;
  joined_at: string;
  email: (string) | null;
  name: (string) | null;
  avatar_url: (string) | null;
}

export interface InviteResponse {
  id: string;
  team_id: string;
  email: string;
  role: string;
  status: string;
  created_at: string;
  expires_at: string;
}

export interface ActivityResponse {
  id: string;
  team_id: string;
  user_id: string;
  activity_type: string;
  created_at: string;
  project_id: (string) | null;
  target_user_id: (string) | null;
  metadata: Record<string, any>;
  user_name: (string) | null;
  user_avatar: (string) | null;
}

// ----- backend/api/template_routes.py -----

export interface TemplatePreview {
  id: string;
  name: string;
  description: string;
  category: string;
  framework: string;
  difficulty: string;
  thumbnail: string;
  tags: (string)[];
  features: (string)[];
  is_premium: boolean;
  is_new: boolean;
  is_popular: boolean;
  downloads: number;
}

export interface CategoryInfo {
  name: string;
  count: number;
  icon: string;
}

// ----- backend/api/terminal_routes.py -----

export interface TerminalMessage {
  message: string;
  session_id?: (string) | null;
  base_path?: (string) | null;
  model?: (string) | null;
}

export interface ToolResult {
  tool_use_id: string;
  result: Record<string, any>;
}

// ----- backend/api/theme_routes.py -----

export interface ColorPaletteUpdate {
  primary?: (string) | null;
  primary_foreground?: (string) | null;
  primary_hover?: (string) | null;
  secondary?: (string) | null;
  accent?: (string) | null;
  background?: (string) | null;
  background_secondary?: (string) | null;
  foreground?: (string) | null;
  foreground_secondary?: (string) | null;
  border?: (string) | null;
  success?: (string) | null;
  warning?: (string) | null;
  error?: (string) | null;
  info?: (string) | null;
  editor_background?: (string) | null;
  editor_foreground?: (string) | null;
  syntax_keyword?: (string) | null;
  syntax_string?: (string) | null;
  syntax_comment?: (string) | null;
  syntax_function?: (string) | null;
}

export interface TypographyUpdate {
  font_sans?: (string) | null;
  font_mono?: (string) | null;
  font_heading?: (string) | null;
  font_size_base?: (string) | null;
}

export interface CreateThemeRequest {
  name?: string;
  description?: string;
  mode?: string;
  base_theme_id?: (string) | null;
  colors?: (Record<string, any>) | null;
  typography?: (Record<string, any>) | null;
  is_public?: boolean;
  tags?: (string)[];
}

export interface UpdateThemeRequest {
  name?: (string) | null;
  description?: (string) | null;
  colors?: (Record<string, any>) | null;
  typography?: (Record<string, any>) | null;
  is_public?: (boolean) | null;
  tags?: ((string)[]) | null;
}

export interface ImportThemeRequest {
  json_data: string;
}

export interface SetUserThemeRequest {
  theme_id: string;
}

export interface ThemeResponse {
  id: string;
  name: string;
  description: string;
  mode: string;
  category: string;
  colors: Record<string, any>;
  typography: Record<string, any>;
  author_id: (string) | null;
  author_name: (string) | null;
  organization_id: (string) | null;
  is_public: boolean;
  downloads: number;
  created_at: string;
  updated_at: string;
  preview_url: (string) | null;
  tags: (string)[];
}

export interface ThemeListResponse {
  themes: (ThemeResponse)[];
  total: number;
}

export interface CSSResponse {
  css: string;
  theme_ids: (string)[];
}

// ----- backend/api/v_core_routes.py -----

export interface CreateOrgRequest {
  name: string;
  plan?: string;
}

export interface CreateUserRequest {
  email: string;
  name: string;
  password?: (string) | null;
}

// (duplicate of InviteRequest from earlier file — skipped)

export interface CreateEntityRequest {
  name: string;
  label: string;
  fields?: (Record<string, any>)[];
}

// (duplicate of CreateRecordRequest from earlier file — skipped)

export interface CreateWorkflowRequest {
  name: string;
  description?: string;
}

export interface AddNodeRequest {
  type: string;
  name: string;
  config?: Record<string, any>;
}

export interface CreateApprovalRequest {
  title: string;
  category: string;
  action_type: string;
  action_data: Record<string, any>;
  priority?: string;
}

// ----- backend/api/version_control_routes.py -----

export interface CreateBranchRequest {
  name: string;
  description?: (string) | null;
}

export interface CreateCommitRequest {
  branch: string;
  message: string;
  files: Record<string, any>;
}

export interface RevertRequest {
  branch: string;
  commit_id: string;
}

export interface MergeRequest {
  source_branch: string;
  target_branch: string;
}

export interface ResolveConflictsRequest {
  branch: string;
  resolutions: Record<string, any>;
  message: string;
}

// ----- backend/api/voice_routes.py -----

export interface ProcessVoiceRequest {
  transcript: string;
  confidence?: number;
  language?: string;
}

export interface UpdateSettingsRequest {
  input_language?: (string) | null;
  output_language?: (string) | null;
  wake_word_enabled?: (boolean) | null;
  wake_word?: (string) | null;
  continuous_listening?: (boolean) | null;
  voice_gender?: (string) | null;
  speech_rate?: (number) | null;
  pitch?: (number) | null;
  volume?: (number) | null;
  read_notifications?: (boolean) | null;
  morning_briefing?: (boolean) | null;
  voice_confirmations?: (boolean) | null;
}

export interface VoiceCommandResponse {
  id: string;
  transcript: string;
  confidence: number;
  language: string;
  category: string;
  intent: string;
  entities: Record<string, any>;
  action: (string) | null;
  response_text: string;
  processing_time_ms: number;
}

// ----- backend/api/vos_routes.py -----

export interface VosClassifyRequest {
  message: string;
  context?: ((Record<string, string>)[]) | null;
}

export interface VosExecuteRequest {
  message: string;
  intent: string;
  context?: ((Record<string, string>)[]) | null;
  source?: string;
  source_id?: (string) | null;
}

export interface VosProcessRequest {
  message: string;
  context?: ((Record<string, string>)[]) | null;
  source?: string;
  source_id?: (string) | null;
}

// ----- backend/api/wizard_routes.py -----

export interface WizardRequest {
  category: string;
  description: string;
  template_id?: (string) | null;
}

export interface WizardResponse {
  project_id: string;
  name: string;
  status: string;
}
